spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unified-financial-analysis-database
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jackson:
    date-format: yyyy-MM-dd